### ISSUE TITLE
Infrastructure: can deploy to AWS

### ISSUE THREAD

**Issue by freyley** [covid19risk/permission-portal#1]
For testing and development purposes, at least, we'll be using AWS. Set up staging and production servers. Should auto deploy from dev branch to staging.

**Comment by rich-dandliker** [comment]
Not sure if this is really needed for v2...suspect it's v3

**Comment by jcolla-holla** [comment]
Goal is to have continuous deployment from `dev` to AWS staging environment to start.

Then can mimic this for a `prod` branch and AWS production environment when we are ready to do so.

Working on this in [this branch](https://github.com/covid19risk/permission-portal/tree/aws)
