### ISSUE TITLE
Add Member Modal UI

### ISSUE THREAD

**Issue by therealnikhil** [covid19risk/permission-portal#101]
Figma v2 now has the add member modal UI for Manage Members screen.
![image](https://user-images.githubusercontent.com/16310780/82155658-87b1dc80-9844-11ea-97ca-81ed8a9ebee6.png)

**Comment by therealnikhil** [comment]
Includes success message
![image](https://user-images.githubusercontent.com/16310780/82155695-d0699580-9844-11ea-87e2-db4af60f9b7f.png)

**Comment by ibeckermayer** [comment]
Need to implement the "X" to close the modal

**Comment by fordacious** [comment]
@ibeckermayer This should be working as of my PR

**Comment by fordacious** [comment]
Closing as it is doneskies
