### ISSUE TITLE
Settings change password flow UI

### ISSUE THREAD

**Issue by therealnikhil** [covid19risk/permission-portal#102]
Change password modal is now in figma v2 design. Firebase provides email password reset out of the box, so all that would be needed is to call the API to reset password and display the success message shown below

**Comment by therealnikhil** [comment]
Includes success message
![image](https://user-images.githubusercontent.com/16310780/82155782-4bcb4700-9845-11ea-8610-16913e96a37d.jpeg)

**Comment by ibeckermayer** [comment]
This flow also doesn't work. We should do this through password reset emails, this dialog could just confirm they want a password reset email sent.

**Comment by ibeckermayer** [comment]
Alternately, if we want to reuse the same dialog for "Forgot password?", we can have them enter their email.

**Comment by therealnikhil** [comment]
We already have the email in the store, so all we'd have to do is show the success/failure message upon clicking forgot password. Success = "Password reset email has been sent"
