### ISSUE TITLE
Unify buttons

### ISSUE THREAD

**Issue by fordacious** [covid19risk/permission-portal#109]
Should also unify the buttons as there are now multiple implementations

Buttons need spinner and disabled state

**Comment by aidan-fitz** [comment]
Based on my conversation with @fordacious:

- Replace "bespoke" dynamic button implementations in various parts of the code (e.g. verify code, login, save) with the `PendingOperationButton`
- Add a disabled state
- Integrate toast control into the `POB`
- Possibly integrate bespoke animations into the `POB`

**Comment by aidan-fitz** [comment]
From @ibeckermayer via Slack:
> Let's make any button for which there's some sort of async operation that we need to wait to complete a PendingOperationButton

From me:
> My intuition is that buttons that update data on the server should use the PendingOperationButton since updating data takes time, but buttons that just close a modal shouldn't because that can happen instantly. So for example, if a form has a "Submit" and a "Reset" button, the submit button should be a POB but the reset should not.
