### ISSUE TITLE
Make mobx react to firestore updates, and make stateful components react to mobx

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#111]
Currently, the app doesn't have a clear architecture for synchronously responding to `Firestore` changes. The simplest way to set up the problem is through an example:

Say there are two admin users (Alex and Bobby) of the same organization, using the app at the same time. If Alex creates a new user, that user should appear on Bobby's "Manage Members" screen, without him having to refresh. Same goes for if Bobby changes something in the "Account Branding" -- Alex should know about it right away.

Firestore provides us a platform for handling this in the form of [document listening ](https://firebase.google.com/docs/firestore/query-data/listen)(`onSnapshot`). We can take advantage of this by architecting the app such that
- mobx runs listeners, that when triggered update the mobx state
- React components are reactive w.r.t. mobx state

With this architecture, components can write directly to Firestore without needing to worry about updating the global state. Additionally, we get multi-client synchronization for free, since other client instances will be listening for such changes and updating state based on them.

**Comment by prabhuinbarajan** [comment]
@ibeckermayer  - Thanks for putting this together. This is definitely a critical capability to have. I see this in the following logical parts:

1. Persistence: This enables the developers to define the model and persist without too much friction.  

2. Data Refresh:  every UI instance subscribing to firebase data changes while adhering to tenancy restrictions (i.e - get me only data changes corresponding to me (user), my organization (if admin), everyone (if super admin)   is another critical function. I am not sure if we can satisfy this requirement exclusively with firebase listeners or whether we should include a service-worker to the frontend. 

3.  Side Effects:  UI's ability to react to data changes (as the listener receives changes to data) by a selective refresh of the DOM.

4. Separation of model vs. view: While we consider this, it would be good to address the logical separation of model from the front end views from a packaging structure and decouple the persistence provider interaction from the views.


For future consideration, as we progress further, we may want to validate the need for schema and data management capabilities on the front end to allow for better testing. i.e - a developer being able to author the model (example - settings), create seed data sets (ex: sample settings for test user accounts) and apply it to firebase and data migration (ex: apply default settings for existing user accounts). This might require front-end to share firebase admin capabilities with the cloud functions.

Does it warrant a design doc on its own or should we address this by a reference implementation?

**Comment by ibeckermayer** [comment]
> 2. Data Refresh:  every UI instance subscribing to firebase data changes while adhering to tenancy restrictions (i.e - get me only data changes corresponding to me (user), my organization (if admin), everyone (if super admin)   is another critical function. I am not sure if we can satisfy this requirement exclusively with firebase listeners or whether we should include a service-worker to the frontend.

I'm 90% sure we can do this exclusively with Firebase listeners

> 3. Side Effects:  UI's ability to react to data changes (as the listener receives changes to data) by a selective refresh of the DOM.

We can wrap React components in `useObserver` which tells React to update the DOM any time a relevant `mobx` store attribute is changed.

> 4. Separation of model vs. view: While we consider this, it would be good to address the logical separation of model from the front end views from a packaging structure and decouple the persistence provider interaction from the views.

My proposal largely achieves this -- model is handled by the mobx store, views are filled in by the objects in the store.

> For future consideration, as we progress further, we may want to validate the need for schema and data management capabilities on the front end to allow for better testing. i.e - a developer being able to author the model (example - settings), create seed data sets (ex: sample settings for test user accounts) and apply it to firebase and data migration (ex: apply default settings for existing user accounts). This might require front-end to share firebase admin capabilities with the cloud functions.

If I understand you correctly, you're saying that we want to be able to seed the database with sample data for testing purposes. I currently have a node script for doing that: `reset-infrastructure.js` (needs maintenance). Would something like that suffice or are you suggesting we need something else?
