### ISSUE TITLE
Add an "X" to the "Add Member" modal

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#113]
<img width="334" alt="Screen Shot 2020-05-19 at 11 03 48 AM" src="https://user-images.githubusercontent.com/13578537/82361954-7261bd00-99c0-11ea-8ca5-d03134bff914.png">
Add the "X" in the top right corner and make it close the Member Modal out. If it's not too much trouble, may as well implement #112 while you're at it

**Comment by aidan-fitz** [comment]
There is already a letter "X" in the modal. I'm guessing that it should be replaced with an "X" close icon. Where can I find such an icon?

**Comment by therealnikhil** [comment]
@aidan-fitz [Figma file](https://www.figma.com/file/kmlg5LIYa955SNkij4CNMn/Covid-Watch---Portal-v2-(dev)). Export as svg

**Comment by aidan-fitz** [comment]
That's probably my night time filter.
