### ISSUE TITLE
"Save Changes" button should only be visible if any changes are made

### ISSUE THREAD

**Issue by therealnikhil** [covid19risk/permission-portal#114]
Reasons:
- Fixes #118 
- In `ManageMembers` save changes is an expensive operation that should only be performed if changes are made
- In general this button is redundant if no changes are made

**Comment by aidan-fitz** [comment]
I don't see this bug. For me, the save changes button does nothing. Can you give us more instructions on how to reproduce the bug?

**Comment by aidan-fitz** [comment]
This wouldn't actually fix #118. If one text box is changed but the other isn't, then saving will cause the unchanged data field to be overwritten with `Loading text...`, but we still want the user to be able to save. But I agree that disabling (graying out) the save button unless the data is changed is a good idea.

**Comment by fordacious** [comment]
@aidan-fitz how far though this are you? I'd made a start on this as part of the button unification change, but you can take it if you want.

**Comment by aidan-fitz** [comment]
@fordacious I worked on #118 and assigned myself to this thinking it would help with that issue. I'm unassigning myself to work on more pressing tasks (v3) for the time being, but I may pick it back up in the future.
