### ISSUE TITLE
Clicking save changes on account branding saves as "Loading text..." if no changes made

### ISSUE THREAD

**Issue by therealnikhil** [covid19risk/permission-portal#118]
If you have time, ideally look at #114 which would fix this

**Comment by aidan-fitz** [comment]
While playing with the `AccountBranding` screen, I noticed that when the text is loaded, the `exposureText` and `diagnosisText` variables are updated in the store, but the corresponding hooks/`State` objects still say `Loading text...`. These `State` objects are updated when the textarea contents are modified and are what get sent to the server when the save button is pressed.

![Account branding window after the text is loaded](https://user-images.githubusercontent.com/2768977/82632663-dce44a00-9bc6-11ea-8833-57d2024a73cb.png)

It seems that I need to make sure that the `State` objects are updated when the data is first fetched from the server. Any pointers on how I could fix this?

**Comment by aidan-fitz** [comment]
It looks like this was fixed by #129. I'll close this out if everyone else agrees.
