### ISSUE TITLE
Unable to update user settings

### ISSUE THREAD

**Issue by aidan-fitz** [covid19risk/permission-portal#137]
Clicking "Save Changes" on the user settings page causes the page to refresh (as in #136), and the new user settings are not saved.

![User settings fail](https://user-images.githubusercontent.com/2768977/82719850-47a38d00-9c7c-11ea-95d4-fc95eb3faaa7.gif)

**Comment by ibeckermayer** [comment]
Closed by https://github.com/covid19risk/permission-portal/pull/169
