### ISSUE TITLE
Forgot Password Reset

### ISSUE THREAD

**Issue by colbymorrison** [covid19risk/permission-portal#153]
Currently clicking on `Forgot Password` and entering email sends the email with link to reset password, but we have not implemented actually resetting the password after following the link. 
![Screen Capture_select-area_20200523133020](https://user-images.githubusercontent.com/20446774/82740008-99d6c380-9cf9-11ea-99bc-c19c1d45f0f5.png)

**Comment by ibeckermayer** [comment]
The email that's sent should contain a link which brings you to a Firebase hosted page, where you can reset your password. Firebase should take care of it all behind the scenes, this design should be considered deprecated until a future more polished version.
