### ISSUE TITLE
Implement tab titles for different screens

### ISSUE THREAD

**Issue by therealnikhil** [covid19risk/permission-portal#162]
- follow the titles on figma v2

**Comment by ibeckermayer** [comment]
I believe you took care of this in your accessibility PR @aidan-fitz ?

**Comment by aidan-fitz** [comment]
I made the page title match the top level heading on each page. I don't see page titles anywhere in the mockup, but maybe I'm missing something.

**Comment by ibeckermayer** [comment]
<img width="693" alt="Screen Shot 2020-05-28 at 10 16 36 AM" src="https://user-images.githubusercontent.com/13578537/83172418-61096680-a0cc-11ea-9d72-cf956da2e148.png">
I think he meant these titles here. But what you put is fine, closing.
