### ISSUE TITLE
Password Reset Successful Toast is not dismissible

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#181]
The "Password Reset Successful" toast on the "My Settings" page isn't dismissible, and blocks the user from opening the menu. (Presumably the failure toast causes a similar problem)

**Comment by aidan-fitz** [comment]
How should the toast behave? Should it have a dismiss button (like an X) or dismiss when clicked/automatically?

**Comment by colbymorrison** [comment]
@aidan-fitz I added a toast in my previous PR so I got a feel for how they work. The toast calls its onClose method after 3 seconds. I think the bug here is that the onClose method of the toast is not setting the correct state variable to false.
