### ISSUE TITLE
Activate / deactivate users

### ISSUE THREAD

**Issue by freyley** [covid19risk/permission-portal#19]
Org admins can activate and deactivate users

User listing shows a filter for active or inactive users, defaults to active users.

**Comment by rich-dandliker** [comment]
Super Admin role can be left until after v3

https://www.notion.so/covidwatch/Permission-Portal-V3-Requirements-151b79bae1f846ae90155d5dcbb9f613#6142edd5499b44ceabd4067dae355f21
