### ISSUE TITLE
Make the new member email sign in link a passwordless email sign in

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#212]
The link that's shown as `https://sign-in-link-here` in the `New Member / Email` frame of the v3 Figma should be a passwordless email sign in link. 

It can be generated in `sendNewUserEmail` using [generateSignInWithEmailLink](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#generatesigninwithemaillink)

**Comment by colbymorrison** [comment]
@ibeckermayer Why is this necessary if we already assign a temporary password? According to the [docs](https://firebase.google.com/docs/auth/web/email-link-auth#completing_sign-in_in_a_web_page) to sign in from a passwordless link you need to re-enter your email. So it seems to be the flow for a new user should be:  

- normal link to homepage in welcome email -> sign in with email and temp password -> prompted to reset password 

OR 

- passwordless link to homepage in welcome email-> enter email -> prompted to reset password. 

Not both. Though I may be missing something here.

**Comment by ibeckermayer** [comment]
Duplicate
