### ISSUE TITLE
Scale down add photo icon

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#221]
Currently our add photo icon (in the Settings page) looks like
<img width="214" alt="Screen Shot 2020-06-08 at 2 57 24 PM" src="https://user-images.githubusercontent.com/13578537/84079846-128f7e00-a990-11ea-8c35-9846c3bdd82c.png">

Scale it down to look more like the Figma
<img width="194" alt="Screen Shot 2020-06-08 at 2 57 05 PM" src="https://user-images.githubusercontent.com/13578537/84079881-21763080-a990-11ea-8fca-f3b222655002.png">

**Comment by aidan-fitz** [comment]
While we're at it, let's use the SVG icon from Figma instead of the PNG version we currently have.
