### ISSUE TITLE
GH action check for logging encapsulation

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#235]
With https://github.com/covid19risk/permission-portal/pull/206 merged, we now want to enforce that all logging goes through our `Logging` util.

We should create a check for this that's run in our GitHub actions or as a `husky` hook that makes sure this is the case.

**Comment by aidan-fitz** [comment]
With #261, `console.*` calls will be caught by Husky during pre-commit. Will that be enough?

**Comment by ibeckermayer** [comment]
> With #261, `console.*` calls will be caught by Husky during pre-commit. Will that be enough?

Yep
