### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#244]
See flow with the same title in [Figma v3](https://www.figma.com/file/UObqudM50aROl5yoCmFqT0/Covid-Watch---Portal-v3-(dev)?node-id=0%3A1) for reference.

One tricky aspect of this might be verifying the user's old password. We should at first try simply calling `signInWithEmailAndPassword` as we do in the `Login.js` page, but this will likely trigger our global login listener which may or may not cause some laggy-ness / general mayhem. If that's not sufficient, we can create a cloud function to verify the old password.

Password can be reset via the [updatePassword](https://firebase.google.com/docs/auth/web/manage-users#set_a_users_password) method

**Comment by colbymorrison** [comment]
This is mostly handled by #241 (yay!) Once that gets all merged, we can refactor out the relevant code to create a Modal for this and a Modal for #214 based on a common component.
