### ISSUE TITLE
Positive Test Validation Flow: Test Validator

### ISSUE THREAD

**Issue by rich-dandliker** [covid19risk/permission-portal#49]
As an Test Validator, I want to be able to validate a positive test requested by an Affected User by entering a code into the Permission Portal so that the RPIs of the Affected User are uploaded to the server and their contacts receive an Exposure Notification.

See [Permission Portal Requirements: Section A](https://www.notion.so/covidwatch/Permission-Portal-V3-Requirements-151b79bae1f846ae90155d5dcbb9f613#42159c7f1c1e495dad705c8805c5bee3)

**Comment by ibeckermayer** [comment]
deprecated
