### ISSUE TITLE
Footer overlaps with content on small screens

### ISSUE THREAD

**Issue by fordacious** [covid19risk/permission-portal#51]
![image](https://user-images.githubusercontent.com/799700/81606597-3a3af880-9388-11ea-980b-cb0289d95e16.png)

A quick fix would be to make the content scrollable and have the footer render a solid white background, such that it renders over the content, OR set the height of the content such that it stops at the height of the footer.

**Comment by therealnikhil** [comment]
Best solution would be to make the footer follow the scrollable content. This issue prevails even when main content is scrollable; footer is positioned at the bottom of the initial screen render and is outside the flow of the rest of the page.
