### ISSUE TITLE
Permission Validation Screen

### ISSUE THREAD

**Issue by freyley** [covid19risk/permission-portal#7]
When a user logs in, they are presented with the permission validation screen for their organization. There are several possible designs for this screen, so don't spend too much time on this for v0.1 - the most basic version simply lists the potential permissions to be validated, and lets the user select one to validate. 

Permissions that can be validated must be:
* Unexpired (i.e. within the last 5 minutes)
* Within the organization

**Comment by rich-dandliker** [comment]
I'm closing this issue- I have more detailed issues covering this funtionality
