### ISSUE TITLE
Footer an doctors style is broken

### ISSUE THREAD

**Issue by fordacious** [covid19risk/permission-portal#76]
Background is off, and it renders above the doctors on the login screen

![image](https://user-images.githubusercontent.com/799700/81983685-9e5bf780-95e8-11ea-8349-e07ba81474f6.png)

![image](https://user-images.githubusercontent.com/799700/81984071-217d4d80-95e9-11ea-8ff4-7e43c2969f45.png)

**Comment by therealnikhil** [comment]
Yes, the footer was temporarily changed to just be below the main component. It was done because the old footer got in the way of manage teams screen, which is now on dev (due to the scrolling issue). @fordacious all these footer issues can be fixed with one PR but no one seems to want to do it...
