### ISSUE TITLE
Ability to delete users

### ISSUE THREAD

**Issue by rich-dandliker** [covid19risk/permission-portal#90]
As an Org Admin, I need the ability to delete user accounts of other users in the Permission Portal so that I can clean up the user store. We need to figure out a way to maintain some record or association with users if we want to have an audit trail. It may be implemented that "deleted accounts" stay in the system for auditability but are no longer visible to admins. Email uniqueness will need to be dealt with in this case as well.

On 5/15/20 we agreed to postpone this feature to after v3.

**Comment by ibeckermayer** [comment]
Switching this back to v3 because we are ahead of schedule

**Comment by fordacious** [comment]
@ibeckermayer looks like this could be closed
